package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

// define structs
type Item struct {
	ShortDescription string  `json:"shortDescription"` // from client
	Price            float64 `json:"price"`            // from client
}

type Items struct {
	Items []Item `json:"items"` // from client
}

type ServerReceipt struct {
	ID           string  `json:"id"`           // from service
	Points       int     `json:"points"`       // from service
	Retailer     string  `json:"retailer"`     // from client
	PurchaseDate string  `json:"purchaseDate"` // from client
	PurchaseTime string  `json:"purchaseTime"` // from client
	Total        float64 `json:"total"`        // from client
	Items        []Item  `json:"items"`        // from client
}

// struct representing inbound receipt
type Receipt struct {
	Retailer     string `json:"retailer"`
	PurchaseDate string `json:"purchaseDate"`
	PurchaseTime string `json:"purchaseTime"`
	Items        []struct {
		ShortDescription string `json:"shortDescription"`
		Price            string `json:"price"`
	} `json:"items"`
	Total string `json:"total"`
}

type Receipts struct {
	ReceiptsMap map[string]Receipt `json:"receipts"` // map of receipts, key is ID
}

// constructor for receipts
func NewReceipts() *Receipts {
	var rs Receipts
	rs.ReceiptsMap = make(map[string]Receipt)
	return &rs
}

// global receipts object
var rs = NewReceipts() // pointer to receipt object, in place of persisting data struct

// setup router
func setupRouter() *gin.Engine {
	r := gin.Default()
	// define routes
	r.GET("/ping", func(c *gin.Context) {
		c.String(http.StatusOK, "pong")
	})
	// process receipt
	r.POST("/receipts/process", processReceipt)
	// get points
	r.GET("/receipts/:id/points", getPoints)

	return r
}

// main function - start server
func main() {
	r := setupRouter()
	// run server
	r.Run(":8080")
}

// Route Functions

// Path: /receipts/process
// Method: POST
// Payload: Receipt JSON
// Response: JSON containing an id for the receipt.
// Description:
// Takes in a JSON receipt (see example in the example directory) and returns a JSON object with an ID generated by your code.
// The ID returned is the ID that should be passed into /receipts/{id}/points to get the number of points the receipt was awarded.
// How many points should be earned are defined by the rules in the README.
// Reminder: Data does not need to survive an application restart. This is to allow you to use in-memory solutions to track any data generated by this endpoint.
func processReceipt(c *gin.Context) {
	// New items, receipt objects
	// var i Items
	var r Receipt
	// var s ServerReceipt

	// generate ID
	id := uuid.New().String()

	// bind JSON to receipt object
	if err := c.BindJSON(&r); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// generate points?

	// append to global Receipts object's map
	(*rs).ReceiptsMap[id] = r

	// return status created and receipt ID
	c.IndentedJSON(http.StatusCreated, gin.H{"id": id})

}

// Path: /receipts/{id}/points
// Method: GET
// Response: A JSON object containing the number of points awarded.
// A simple Getter endpoint that looks up the receipt by the ID and returns an object specifying the points awarded.
func getPoints(c *gin.Context) {
	// get ID
	id := c.Param("id")
	// get receipt object with ID from receipts
	r, present := (*rs).ReceiptsMap[id]
	if !present {
		c.IndentedJSON(http.StatusNotFound, gin.H{"error": "receipt not found"})
		return
	} else {
		c.IndentedJSON(http.StatusOK, gin.H{"points": r.Points})
	}

}
